name: ci
on:
  push:
    branches:
      - develop
      - master
      - manual-offline-build
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force

  build-offline:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/manual-offline-build'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install dependencies
        run: pip install mkdocs-material
      - name: Build offline manual
        env:
          OFFLINE: "true"
        run: mkdocs build -d csound7-manual-offline
      - name: Package offline manual
        run: zip -r csound7-manual-offline.zip csound7-manual-offline/
      - name: Delete previous dev release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if gh release view latest --json isPrerelease --jq '.isPrerelease' | grep -q true; then
            gh release delete latest --yes --cleanup-tag
          fi
      - name: Update latest release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Development Build
          prerelease: true
          files: csound7-manual-offline.zip
          
